package com.wiproworkspan.db2.repo;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.wiproworkspan.db2.entity.JobDependencies;

public interface ShowDependRepo extends JpaRepository<JobDependencies, Integer> {
	
	@Query(value="SELECT 'PARENT' DefinedAs,\r\n"
			+ "							xjd.parent_Schedule_id,\r\n"
			+ "							xjsparent.Schedule_Name         parent_Schedule_Name,\r\n"
			+ "							Parentxseh.execution_id         Parent_last_execution_id,\r\n"
			+ "							Parentxseh.execution_start_date Parent_last_execution_start_date,\r\n"
			+ "							Parentxseh.execution_end_date   Parent_last_execution_end_date,\r\n"
			+ "							Parentxseh.execution_status     Parent_last_execution_status,\r\n"
			+ "							\r\n"
			+ "                            IFNULL(\r\n"
			+ "    xjsparent.Next_Scheduled_run_date,\r\n"
			+ "    STR_TO_DATE(CONCAT(DATE(xjsparent.Schedule_start_date), ' ', TIME(xjsparent.Resubmit_time)), '%Y-%m-%d %H:%i:%s')\r\n"
			+ ") AS nextScheduleRunDate\r\n"
			+ "			\r\n"
			+ "						FROM xxws_job_dependencies xjd\r\n"
			+ "							INNER JOIN xxws_job_schedules xjsparent\r\n"
			+ "								ON (xjsparent.Schedule_id = xjd.parent_Schedule_id)\r\n"
			+ "							INNER JOIN xxws_job_schedules xjschild\r\n"
			+ "								ON (    xjschild.schedule_id = xjd.schedule_id\r\n"
			+ "									AND xjschild.schedule_id = :sch_id)\r\n"
			+ "							LEFT OUTER JOIN\r\n"
			+ "							(SELECT *\r\n"
			+ "								FROM xxws_schedule_execution_history child\r\n"
			+ "								WHERE child.execution_start_date =\r\n"
			+ "										(SELECT (execution_start_date)\r\n"
			+ "											FROM xxws_schedule_execution_history xseh\r\n"
			+ "											WHERE     execution_start_date <\r\n"
			+ "														(SELECT (execution_start_date)\r\n"
			+ "															FROM xxws_schedule_execution_history\r\n"
			+ "																xseh1\r\n"
			+ "														WHERE     xseh.schedule_id =\r\n"
			+ "																		xseh1.schedule_id\r\n"
			+ "																AND xseh1.execution_status =\r\n"
			+ "																		'COMPLETED' order by execution_start_date desc limit 1)\r\n"
			+ "												AND xseh.schedule_id = child.schedule_id)  order by execution_start_date desc limit 1) \r\n"
			+ "							ChildlastExecution\r\n"
			+ "								ON (ChildlastExecution.schedule_id = xjschild.schedule_id)\r\n"
			+ "							LEFT OUTER JOIN xxws_schedule_execution_history Parentxseh\r\n"
			+ "								ON (    xjsparent.Schedule_id = Parentxseh.schedule_id\r\n"
			+ "									AND Parentxseh.execution_start_date >\r\n"
			+ "											IFNULL(\r\n"
			+ "    ChildlastExecution.execution_start_date,\r\n"
			+ "    STR_TO_DATE(CONCAT('1900-01-01', ' 00:00:00'), '%Y-%m-%d %H:%i:%s')\r\n"
			+ ") )\r\n"
			+ "						UNION ALL\r\n"
			+ "						SELECT 'CHILD' DefinedAs,\r\n"
			+ "							xjschild.Schedule_id,\r\n"
			+ "							xjschild.Schedule_Name         child_Schedule_Name,\r\n"
			+ "							Childxseh.execution_id         child_last_execution_id,\r\n"
			+ "							Childxseh.execution_start_date child_last_execution_start_date,\r\n"
			+ "							Childxseh.execution_end_date   child_last_execution_end_date,\r\n"
			+ "							Childxseh.execution_status     child_last_execution_status,\r\n"
			+ "							IFNULL(\r\n"
			+ "    xjschild.Next_Scheduled_run_date,\r\n"
			+ "    STR_TO_DATE(CONCAT(DATE(xjschild.Schedule_start_date), ' ', TIME(xjschild.Resubmit_time)), '%Y-%m-%d %H:%i:%s')\r\n"
			+ ") AS nextScheduleRunDate\r\n"
			+ "						FROM xxws_job_dependencies xjd\r\n"
			+ "							INNER JOIN xxws_job_schedules xjsparent\r\n"
			+ "								ON (    xjsparent.Schedule_id = xjd.parent_Schedule_id\r\n"
			+ "									AND xjsparent.schedule_id = :sch_id)\r\n"
			+ "							INNER JOIN xxws_job_schedules xjschild\r\n"
			+ "								ON (xjschild.schedule_id = xjd.schedule_id)\r\n"
			+ "							LEFT OUTER JOIN\r\n"
			+ "							(SELECT *\r\n"
			+ "								FROM xxws_schedule_execution_history parent\r\n"
			+ "								WHERE parent.execution_start_date =\r\n"
			+ "										(SELECT  (execution_start_date)\r\n"
			+ "											FROM xxws_schedule_execution_history xseh\r\n"
			+ "											WHERE     execution_start_date <\r\n"
			+ "														(SELECT  (execution_start_date)\r\n"
			+ "															FROM xxws_schedule_execution_history\r\n"
			+ "																xseh1\r\n"
			+ "														WHERE     xseh.schedule_id =\r\n"
			+ "																		xseh1.schedule_id\r\n"
			+ "																AND xseh1.execution_status =\r\n"
			+ "																		'COMPLETED' order by execution_start_date desc limit 1)\r\n"
			+ "												AND xseh.schedule_id = parent.schedule_id order by execution_start_date desc limit 1))\r\n"
			+ "							ParentlastExecution\r\n"
			+ "								ON (ParentlastExecution.schedule_id = xjsparent.schedule_id)\r\n"
			+ "							LEFT OUTER JOIN xxws_schedule_execution_history Childxseh\r\n"
			+ "								ON (    xjsparent.Schedule_id = Childxseh.schedule_id\r\n"
			+ "									AND Childxseh.execution_start_date <\r\n"
			+ "											IFNULL(\r\n"
			+ "    ParentlastExecution.execution_start_date,\r\n"
			+ "    STR_TO_DATE(CONCAT('1900-01-01', ' ', '00:00:00'), '%Y-%m-%d %H:%i:%s')\r\n"
			+ ") )\r\n"
			+ "						ORDER BY 1 desc,8, 3",nativeQuery=true)
	List<Object[]> findByShowdependencies(@Param("sch_id") int sch_id);

}
